eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.default-zone=http://localhost:8761/eureka

# 1. Tell Micrometer to trace 100% of requests (Default is 10%, which is confusing in dev!)
management.tracing.sampling.probability=1.0

# 2. Tell the services where the Zipkin server lives
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

logging.level.zipkin2=DEBUG
