eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.default-zone=http://localhost:8761/eureka


management.tracing.sampling.probability=1.0


#management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

management.zipkin.tracing.endpoint=http://127.0.0.1:9411/api/v2/spans

# Force the tracer to activate regardless of environment defaults
management.tracing.enabled=true

# Expose the actuator endpoints so the Observation registry fully binds
management.endpoints.web.exposure.include=*

# Logs Brave tracing lifecycle actions (Span creation/finishing)
logging.level.brave.tracer=TRACE

# Logs Zipkin Reporter network transmissions (HTTP posts to http://localhost:9411)
logging.level.zipkin2.reporter=TRACE

# Watch Spring's internal HTTP client actually send the JSON payload to port 9411
logging.level.org.springframework.web.client.RestTemplate=TRACE

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
